version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - - "8080:8080"
    environment:
      SERVER_ADDRESS: ${SERVER_ADDRESS}
      POSTGRES_CONN: ${POSTGRES_CONN}
      POSTGRES_JDBC_URL: ${POSTGRES_JDBC_URL}
      POSTGRES_USERNAME: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_DATABASE: ${POSTGRES_DATABASE}
    env_file:
      - .env